name: AI Test Automation Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run AI Test Generation
        run: |
          source venv/bin/activate
          python models/test_generator.py

      - name: Run Pytest and Generate HTML Report
        continue-on-error: true  # Prevents pipeline failure on test failures
        run: |
          source venv/bin/activate
          pytest tests/ai_generated_tests.py --html=results/test_report.html | tee results/test_failures.log

      - name: Upload Failure Logs for Self-Learning
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test_failures
          path: results/test_failures.log

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: results/test_report.html
